export { default as HomePage } from "./HomePage"
export { default as HerosPage } from "./HerosPage"
export { default as HeroPage } from "./HeroPage"
export { default as SearchPage } from "./SearchPage"
export { default as NotFoundPage } from "./NotFoundPage"